### ISSUE TITLE
'gdk_pixbuf_new_from_file' could not be found

### ISSUE THREAD

**Issue by FriedrichFroebel** [Cimbali/pympress#32]
I just tried to use the latest `master`, but could not get it to run (tested on Windows 8.1 with Python 3.4, no error on Ubuntu with Python3.5).

Seems like there is some error with the orientation value:

```
ERROR:pympress.ui:Invalid layout
Traceback (most recent call last):
  File "C:\Users\Me\Documents\pympress\pympress\ui.py", line 633, in make_pwin
    self.validate_layout(self.notes_layout, set(self.placeable_widgets.keys()) - {"annotations"})
  File "C:\Users\Me\Documents\pympress\pympress\ui.py", line 447, in validate_layout
    raise ValueError('"orientation" is mandatory and must be "horizontal" or "vertical" at node {}'.format(w_desc))
ValueError: "orientation" is mandatory and must be "horizontal" or "vertical" at node {}
ERROR:pympress.ui:Invalid layout
Traceback (most recent call last):
  File "C:\Users\Me\Documents\pympress\pympress\ui.py", line 640, in make_pwin
    self.validate_layout(self.plain_layout, set(self.placeable_widgets.keys()) - {"notes"})
  File "C:\Users\Me\Documents\pympress\pympress\ui.py", line 447, in validate_layout
    raise ValueError('"orientation" is mandatory and must be "horizontal" or "vertical" at node {}'.format(w_desc))
ValueError: "orientation" is mandatory and must be "horizontal" or "vertical" at node {}
```

There seems to be another error which seems to occur on Windows only:

```
CRITICAL:__main__:Uncaught exception:
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Me\Documents\pympress\pympress\__main__.py", line 123, in <module>
    main()
  File "C:\Users\Me\Documents\pympress\pympress\__main__.py", line 116, in main
    ui = pympress.ui.UI(ett, name)
  File "C:\Users\Me\Documents\pympress\pympress\ui.py", line 329, in __init__
    self.make_pwin()
  File "C:\Users\Me\Documents\pympress\pympress\ui.py", line 645, in make_pwin
    self.rearrange_p_layout(self.notes_layout if self.notes_mode else self.plain_layout)
  File "C:\Users\Me\Documents\pympress\pympress\ui.py", line 618, in rearrange_p_layout
    self.load_pointer(default)
  File "C:\Users\Me\Documents\pympress\pympress\ui.py", line 2114, in load_pointer
    self.pointer = pympress.util.get_icon_pixbuf(name + '.png')
  File "C:\Users\Me\Documents\pympress\pympress\util.py", line 107, in get_icon_pixbuf
    return GdkPixbuf.Pixbuf.new_from_file(get_resource_path('share', 'pixmaps', name))
GLib.Error: g-invoke-error-quark: Could not locate gdk_pixbuf_new_from_file: 'gdk_pixbuf_new_from_file': The specified procedure could not be found. (1)
```

**Comment by Cimbali** [comment]
Hi @friedrichfroebel, the first error seems to be due to your configuration of the layout. It's in the "layout" section in the configuration file, which in windows is at `%APPDATA%/pympress.ini`.

It contains a value that doesn't pass validation, try deleting it which should fix that. If you didn't modify it ,that means pympress doesn't upgrade smoothly from an old version file.

The second bug seems to be a missing file in the `share/pixmaps` folder, specifically the `pointer_red.png`. Could you check it's there?

**Comment by Cimbali** [comment]
Wait, my bad, what's missing is the `gdk_pixbuf_new_from_file` function, that should be provided by the `Gdk.GdkPixbuf`.

I'll check if this is normal, in which case we'll add a different loading method as fallback. Otherwise it's probably an problem with your PyGi installation.

**Comment by Cimbali** [comment]
https://stackoverflow.com/q/41122463/1387346

**Comment by FriedrichFroebel** [comment]
After getting the layout error, I tried to rename the old ini file to get a new one created on the next startup. As I am still getting this error without the `pympress.ini`, there seems to be something broken.

**Comment by FriedrichFroebel** [comment]
After getting the layout error, I tried to rename the old ini file to get a new one created on the next startup and still got this error as the `pympress.ini` file could not be written because of the Pixbuf problem.

During an update of my PyGi installation, I discovered that the `Gdk-Pixbuf` package has to be selected separately. Adding it to the list of the packages to install all issues were resolved as the `pympress.ini` could be written now, too. This should probably be mentioned inside the README.
